/*
 * generated by Xtext 2.12.0
 */
package com.kaleidoscope.usecase.showcase.xtext.ui;

import com.google.inject.Injector;
import com.kaleidoscope.usecase.showcase.xtext.PersonDsl.ui.internal.PersonDslActivator;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class PersonDslExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return PersonDslActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return PersonDslActivator.getInstance().getInjector(PersonDslActivator.COM_KALEIDOSCOPE_USECASE_SHOWCASE_XTEXT_PERSONDSL);
	}
	
}
