/*
 * generated by Xtext 2.12.0
 */
package com.kaleidoscope.usecase.showcase.xtext.ide.contentassist.antlr;

import com.google.inject.Inject;
import com.kaleidoscope.usecase.showcase.xtext.ide.contentassist.antlr.internal.InternalEmployeeDslParser;
import com.kaleidoscope.usecase.showcase.xtext.services.EmployeeDslGrammarAccess;
import java.util.HashMap;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;

public class EmployeeDslParser extends AbstractContentAssistParser {

	@Inject
	private EmployeeDslGrammarAccess grammarAccess;

	private Map<AbstractElement, String> nameMappings;

	@Override
	protected InternalEmployeeDslParser createParser() {
		InternalEmployeeDslParser result = new InternalEmployeeDslParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getEStringAccess().getAlternatives(), "rule__EString__Alternatives");
					put(grammarAccess.getEmployeeAccess().getGroup(), "rule__Employee__Group__0");
					put(grammarAccess.getEmployeeAccess().getGroup_4(), "rule__Employee__Group_4__0");
					put(grammarAccess.getEmployeeAccess().getGroup_5(), "rule__Employee__Group_5__0");
					put(grammarAccess.getEIntAccess().getGroup(), "rule__EInt__Group__0");
					put(grammarAccess.getEmployeeContainerAccess().getEmployeesAssignment(), "rule__EmployeeContainer__EmployeesAssignment");
					put(grammarAccess.getEmployeeAccess().getIDAssignment_2(), "rule__Employee__IDAssignment_2");
					put(grammarAccess.getEmployeeAccess().getNameAssignment_4_1(), "rule__Employee__NameAssignment_4_1");
					put(grammarAccess.getEmployeeAccess().getSalaryAssignment_5_1(), "rule__Employee__SalaryAssignment_5_1");
				}
			};
		}
		return nameMappings.get(element);
	}
			
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public EmployeeDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(EmployeeDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
