/*
 * generated by Xtext 2.12.0
 */
package com.kaleidoscope.usecase.showcase.xtext.parser.antlr;

import com.google.inject.Inject;
import com.kaleidoscope.usecase.showcase.xtext.parser.antlr.internal.InternalPersonDslParser;
import com.kaleidoscope.usecase.showcase.xtext.services.PersonDslGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class PersonDslParser extends AbstractAntlrParser {

	@Inject
	private PersonDslGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalPersonDslParser createParser(XtextTokenStream stream) {
		return new InternalPersonDslParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "PersonContainer";
	}

	public PersonDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(PersonDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
