/**
 * generated by Xtext 2.12.0
 */
package com.kaleidoscope.usecase.showcase.xtext.ui.contentassist;

import com.kaleidoscope.usecase.showcase.xtext.ui.contentassist.AbstractEmployeeDslProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class EmployeeDslProposalProvider extends AbstractEmployeeDslProposalProvider {
}
