/*
 * generated by Xtext 2.12.0
 */
package com.kaleidoscope.usecase.showcase.xtext.ide


/**
 * Use this class to register ide components.
 */
class PersonDslIdeModule extends AbstractPersonDslIdeModule {
}
