/**
 * generated by Xtext 2.12.0
 */
package com.kaleidoscope.usecase.showcase.xtext.employeeDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Employee</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.kaleidoscope.usecase.showcase.xtext.employeeDsl.Employee#getID <em>ID</em>}</li>
 *   <li>{@link com.kaleidoscope.usecase.showcase.xtext.employeeDsl.Employee#getName <em>Name</em>}</li>
 *   <li>{@link com.kaleidoscope.usecase.showcase.xtext.employeeDsl.Employee#getSalary <em>Salary</em>}</li>
 * </ul>
 *
 * @see com.kaleidoscope.usecase.showcase.xtext.employeeDsl.EmployeeDslPackage#getEmployee()
 * @model
 * @generated
 */
public interface Employee extends EObject
{
  /**
   * Returns the value of the '<em><b>ID</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>ID</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>ID</em>' attribute.
   * @see #setID(int)
   * @see com.kaleidoscope.usecase.showcase.xtext.employeeDsl.EmployeeDslPackage#getEmployee_ID()
   * @model
   * @generated
   */
  int getID();

  /**
   * Sets the value of the '{@link com.kaleidoscope.usecase.showcase.xtext.employeeDsl.Employee#getID <em>ID</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>ID</em>' attribute.
   * @see #getID()
   * @generated
   */
  void setID(int value);

  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see com.kaleidoscope.usecase.showcase.xtext.employeeDsl.EmployeeDslPackage#getEmployee_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link com.kaleidoscope.usecase.showcase.xtext.employeeDsl.Employee#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Salary</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Salary</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Salary</em>' attribute.
   * @see #setSalary(int)
   * @see com.kaleidoscope.usecase.showcase.xtext.employeeDsl.EmployeeDslPackage#getEmployee_Salary()
   * @model
   * @generated
   */
  int getSalary();

  /**
   * Sets the value of the '{@link com.kaleidoscope.usecase.showcase.xtext.employeeDsl.Employee#getSalary <em>Salary</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Salary</em>' attribute.
   * @see #getSalary()
   * @generated
   */
  void setSalary(int value);

} // Employee
