/*
 * generated by Xtext 2.12.0
 */
package com.kaleidoscope.usecase.showcase.xtext.ui;

import com.google.inject.Injector;
import com.kaleidoscope.usecase.showcase.xtext.EmployeeDsl.ui.internal.EmployeeDslActivator;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class EmployeeDslExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return EmployeeDslActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return EmployeeDslActivator.getInstance().getInjector(EmployeeDslActivator.COM_KALEIDOSCOPE_USECASE_SHOWCASE_XTEXT_EMPLOYEEDSL);
	}
	
}
