/*
 * generated by Xtext 2.12.0
 */
package com.kaleidoscope.usecase.showcase.xtext.parser.antlr;

import com.google.inject.Inject;
import com.kaleidoscope.usecase.showcase.xtext.parser.antlr.internal.InternalEmployeeDslParser;
import com.kaleidoscope.usecase.showcase.xtext.services.EmployeeDslGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class EmployeeDslParser extends AbstractAntlrParser {

	@Inject
	private EmployeeDslGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalEmployeeDslParser createParser(XtextTokenStream stream) {
		return new InternalEmployeeDslParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "EmployeeContainer";
	}

	public EmployeeDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(EmployeeDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
