/**
 * generated by Xtext 2.12.0
 */
package com.kaleidoscope.usecase.showcase.xtext.ui;

import com.kaleidoscope.usecase.showcase.xtext.ui.AbstractEmployeeDslUiModule;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class EmployeeDslUiModule extends AbstractEmployeeDslUiModule {
  public EmployeeDslUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
