/*
 * generated by Xtext 2.12.0
 */
package com.kaleidoscope.usecase.showcase.xtext.ide.contentassist.antlr;

import com.google.inject.Inject;
import com.kaleidoscope.usecase.showcase.xtext.ide.contentassist.antlr.internal.InternalPersonDslParser;
import com.kaleidoscope.usecase.showcase.xtext.services.PersonDslGrammarAccess;
import java.util.HashMap;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;

public class PersonDslParser extends AbstractContentAssistParser {

	@Inject
	private PersonDslGrammarAccess grammarAccess;

	private Map<AbstractElement, String> nameMappings;

	@Override
	protected InternalPersonDslParser createParser() {
		InternalPersonDslParser result = new InternalPersonDslParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getEStringAccess().getAlternatives(), "rule__EString__Alternatives");
					put(grammarAccess.getPersonAccess().getGroup(), "rule__Person__Group__0");
					put(grammarAccess.getPersonAccess().getGroup_4(), "rule__Person__Group_4__0");
					put(grammarAccess.getEIntAccess().getGroup(), "rule__EInt__Group__0");
					put(grammarAccess.getPersonContainerAccess().getPersonsAssignment(), "rule__PersonContainer__PersonsAssignment");
					put(grammarAccess.getPersonAccess().getIDAssignment_2(), "rule__Person__IDAssignment_2");
					put(grammarAccess.getPersonAccess().getNameAssignment_4_1(), "rule__Person__NameAssignment_4_1");
				}
			};
		}
		return nameMappings.get(element);
	}
			
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public PersonDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(PersonDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
