/**
 * generated by Xtext 2.12.0
 */
package com.kaleidoscope.usecase.showcase.xtext.personDsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Person Container</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.kaleidoscope.usecase.showcase.xtext.personDsl.PersonContainer#getPersons <em>Persons</em>}</li>
 * </ul>
 *
 * @see com.kaleidoscope.usecase.showcase.xtext.personDsl.PersonDslPackage#getPersonContainer()
 * @model
 * @generated
 */
public interface PersonContainer extends EObject
{
  /**
   * Returns the value of the '<em><b>Persons</b></em>' containment reference list.
   * The list contents are of type {@link com.kaleidoscope.usecase.showcase.xtext.personDsl.Person}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Persons</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Persons</em>' containment reference list.
   * @see com.kaleidoscope.usecase.showcase.xtext.personDsl.PersonDslPackage#getPersonContainer_Persons()
   * @model containment="true"
   * @generated
   */
  EList<Person> getPersons();

} // PersonContainer
