/**
 * generated by Xtext 2.12.0
 */
package com.kaleidoscope.usecase.showcase.xtext.personDsl;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see com.kaleidoscope.usecase.showcase.xtext.personDsl.PersonDslFactory
 * @model kind="package"
 * @generated
 */
public interface PersonDslPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "personDsl";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.kaleidoscope.com/usecase/showcase/xtext/PersonDsl";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "personDsl";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  PersonDslPackage eINSTANCE = com.kaleidoscope.usecase.showcase.xtext.personDsl.impl.PersonDslPackageImpl.init();

  /**
   * The meta object id for the '{@link com.kaleidoscope.usecase.showcase.xtext.personDsl.impl.PersonContainerImpl <em>Person Container</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.kaleidoscope.usecase.showcase.xtext.personDsl.impl.PersonContainerImpl
   * @see com.kaleidoscope.usecase.showcase.xtext.personDsl.impl.PersonDslPackageImpl#getPersonContainer()
   * @generated
   */
  int PERSON_CONTAINER = 0;

  /**
   * The feature id for the '<em><b>Persons</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PERSON_CONTAINER__PERSONS = 0;

  /**
   * The number of structural features of the '<em>Person Container</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PERSON_CONTAINER_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link com.kaleidoscope.usecase.showcase.xtext.personDsl.impl.PersonImpl <em>Person</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.kaleidoscope.usecase.showcase.xtext.personDsl.impl.PersonImpl
   * @see com.kaleidoscope.usecase.showcase.xtext.personDsl.impl.PersonDslPackageImpl#getPerson()
   * @generated
   */
  int PERSON = 1;

  /**
   * The feature id for the '<em><b>ID</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PERSON__ID = 0;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PERSON__NAME = 1;

  /**
   * The number of structural features of the '<em>Person</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PERSON_FEATURE_COUNT = 2;


  /**
   * Returns the meta object for class '{@link com.kaleidoscope.usecase.showcase.xtext.personDsl.PersonContainer <em>Person Container</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Person Container</em>'.
   * @see com.kaleidoscope.usecase.showcase.xtext.personDsl.PersonContainer
   * @generated
   */
  EClass getPersonContainer();

  /**
   * Returns the meta object for the containment reference list '{@link com.kaleidoscope.usecase.showcase.xtext.personDsl.PersonContainer#getPersons <em>Persons</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Persons</em>'.
   * @see com.kaleidoscope.usecase.showcase.xtext.personDsl.PersonContainer#getPersons()
   * @see #getPersonContainer()
   * @generated
   */
  EReference getPersonContainer_Persons();

  /**
   * Returns the meta object for class '{@link com.kaleidoscope.usecase.showcase.xtext.personDsl.Person <em>Person</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Person</em>'.
   * @see com.kaleidoscope.usecase.showcase.xtext.personDsl.Person
   * @generated
   */
  EClass getPerson();

  /**
   * Returns the meta object for the attribute '{@link com.kaleidoscope.usecase.showcase.xtext.personDsl.Person#getID <em>ID</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>ID</em>'.
   * @see com.kaleidoscope.usecase.showcase.xtext.personDsl.Person#getID()
   * @see #getPerson()
   * @generated
   */
  EAttribute getPerson_ID();

  /**
   * Returns the meta object for the attribute '{@link com.kaleidoscope.usecase.showcase.xtext.personDsl.Person#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see com.kaleidoscope.usecase.showcase.xtext.personDsl.Person#getName()
   * @see #getPerson()
   * @generated
   */
  EAttribute getPerson_Name();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  PersonDslFactory getPersonDslFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link com.kaleidoscope.usecase.showcase.xtext.personDsl.impl.PersonContainerImpl <em>Person Container</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.kaleidoscope.usecase.showcase.xtext.personDsl.impl.PersonContainerImpl
     * @see com.kaleidoscope.usecase.showcase.xtext.personDsl.impl.PersonDslPackageImpl#getPersonContainer()
     * @generated
     */
    EClass PERSON_CONTAINER = eINSTANCE.getPersonContainer();

    /**
     * The meta object literal for the '<em><b>Persons</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PERSON_CONTAINER__PERSONS = eINSTANCE.getPersonContainer_Persons();

    /**
     * The meta object literal for the '{@link com.kaleidoscope.usecase.showcase.xtext.personDsl.impl.PersonImpl <em>Person</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.kaleidoscope.usecase.showcase.xtext.personDsl.impl.PersonImpl
     * @see com.kaleidoscope.usecase.showcase.xtext.personDsl.impl.PersonDslPackageImpl#getPerson()
     * @generated
     */
    EClass PERSON = eINSTANCE.getPerson();

    /**
     * The meta object literal for the '<em><b>ID</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PERSON__ID = eINSTANCE.getPerson_ID();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PERSON__NAME = eINSTANCE.getPerson_Name();

  }

} //PersonDslPackage
