/**
 * generated by Xtext 2.12.0
 */
package com.kaleidoscope.usecase.showcase.xtext.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import com.kaleidoscope.usecase.showcase.xtext.PersonDslRuntimeModule;
import com.kaleidoscope.usecase.showcase.xtext.PersonDslStandaloneSetup;
import com.kaleidoscope.usecase.showcase.xtext.ide.PersonDslIdeModule;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class PersonDslIdeSetup extends PersonDslStandaloneSetup {
  @Override
  public Injector createInjector() {
    PersonDslRuntimeModule _personDslRuntimeModule = new PersonDslRuntimeModule();
    PersonDslIdeModule _personDslIdeModule = new PersonDslIdeModule();
    return Guice.createInjector(Modules2.mixin(_personDslRuntimeModule, _personDslIdeModule));
  }
}
