/**
 * generated by Xtext 2.12.0
 */
package com.kaleidoscope.usecase.showcase.xtext.ide;

import com.kaleidoscope.usecase.showcase.xtext.ide.AbstractPersonDslIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class PersonDslIdeModule extends AbstractPersonDslIdeModule {
}
