grammar com.kaleidoscope.usecase.showcase.xtext.PersonDsl with org.eclipse.xtext.common.Terminals

generate personDsl "http://www.kaleidoscope.com/usecase/showcase/xtext/PersonDsl"
import "http://www.eclipse.org/emf/2002/Ecore" as ecore

PersonContainer:
	persons+=Person*;
	
Person returns Person:
	{Person}
	'Person'
	ID=EInt
	'{'
		('name' name=EString)?
	'}';

EString returns ecore::EString:
	STRING | ID;

EInt returns ecore::EInt:
	'-'? INT;
	