/*
 * generated by Xtext 2.12.0
 */
package com.kaleidoscope.usecase.showcase.xtext


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class PersonDslRuntimeModule extends AbstractPersonDslRuntimeModule {
}
